// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

// Protobuf Java Version: 3.25.3
package com.moon.link.common.domain.protobuf;

/**
 * Protobuf type {@code com.moon.link.common.domain.protobuf.CompleteMessage}
 */
public final class CompleteMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.moon.link.common.domain.protobuf.CompleteMessage)
    CompleteMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompleteMessage.newBuilder() to construct.
  private CompleteMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompleteMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompleteMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moon.link.common.domain.protobuf.CompleteMessage.class, com.moon.link.common.domain.protobuf.CompleteMessage.Builder.class);
  }

  private int bitField0_;
  public static final int PACKET_HEADER_FIELD_NUMBER = 1;
  private com.moon.link.common.domain.protobuf.PacketHeader packetHeader_;
  /**
   * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   * @return Whether the packetHeader field is set.
   */
  @java.lang.Override
  public boolean hasPacketHeader() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   * @return The packetHeader.
   */
  @java.lang.Override
  public com.moon.link.common.domain.protobuf.PacketHeader getPacketHeader() {
    return packetHeader_ == null ? com.moon.link.common.domain.protobuf.PacketHeader.getDefaultInstance() : packetHeader_;
  }
  /**
   * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   */
  @java.lang.Override
  public com.moon.link.common.domain.protobuf.PacketHeaderOrBuilder getPacketHeaderOrBuilder() {
    return packetHeader_ == null ? com.moon.link.common.domain.protobuf.PacketHeader.getDefaultInstance() : packetHeader_;
  }

  public static final int PACKET_BODY_FIELD_NUMBER = 2;
  private com.moon.link.common.domain.protobuf.PacketBody packetBody_;
  /**
   * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   * @return Whether the packetBody field is set.
   */
  @java.lang.Override
  public boolean hasPacketBody() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   * @return The packetBody.
   */
  @java.lang.Override
  public com.moon.link.common.domain.protobuf.PacketBody getPacketBody() {
    return packetBody_ == null ? com.moon.link.common.domain.protobuf.PacketBody.getDefaultInstance() : packetBody_;
  }
  /**
   * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   */
  @java.lang.Override
  public com.moon.link.common.domain.protobuf.PacketBodyOrBuilder getPacketBodyOrBuilder() {
    return packetBody_ == null ? com.moon.link.common.domain.protobuf.PacketBody.getDefaultInstance() : packetBody_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getPacketHeader());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getPacketBody());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPacketHeader());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPacketBody());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moon.link.common.domain.protobuf.CompleteMessage)) {
      return super.equals(obj);
    }
    com.moon.link.common.domain.protobuf.CompleteMessage other = (com.moon.link.common.domain.protobuf.CompleteMessage) obj;

    if (hasPacketHeader() != other.hasPacketHeader()) return false;
    if (hasPacketHeader()) {
      if (!getPacketHeader()
          .equals(other.getPacketHeader())) return false;
    }
    if (hasPacketBody() != other.hasPacketBody()) return false;
    if (hasPacketBody()) {
      if (!getPacketBody()
          .equals(other.getPacketBody())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPacketHeader()) {
      hash = (37 * hash) + PACKET_HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getPacketHeader().hashCode();
    }
    if (hasPacketBody()) {
      hash = (37 * hash) + PACKET_BODY_FIELD_NUMBER;
      hash = (53 * hash) + getPacketBody().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.moon.link.common.domain.protobuf.CompleteMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.moon.link.common.domain.protobuf.CompleteMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moon.link.common.domain.protobuf.CompleteMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moon.link.common.domain.protobuf.CompleteMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.moon.link.common.domain.protobuf.CompleteMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.moon.link.common.domain.protobuf.CompleteMessage)
      com.moon.link.common.domain.protobuf.CompleteMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.link.common.domain.protobuf.CompleteMessage.class, com.moon.link.common.domain.protobuf.CompleteMessage.Builder.class);
    }

    // Construct using com.moon.link.common.domain.protobuf.CompleteMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPacketHeaderFieldBuilder();
        getPacketBodyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      packetHeader_ = null;
      if (packetHeaderBuilder_ != null) {
        packetHeaderBuilder_.dispose();
        packetHeaderBuilder_ = null;
      }
      packetBody_ = null;
      if (packetBodyBuilder_ != null) {
        packetBodyBuilder_.dispose();
        packetBodyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_descriptor;
    }

    @java.lang.Override
    public com.moon.link.common.domain.protobuf.CompleteMessage getDefaultInstanceForType() {
      return com.moon.link.common.domain.protobuf.CompleteMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.moon.link.common.domain.protobuf.CompleteMessage build() {
      com.moon.link.common.domain.protobuf.CompleteMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moon.link.common.domain.protobuf.CompleteMessage buildPartial() {
      com.moon.link.common.domain.protobuf.CompleteMessage result = new com.moon.link.common.domain.protobuf.CompleteMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.moon.link.common.domain.protobuf.CompleteMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.packetHeader_ = packetHeaderBuilder_ == null
            ? packetHeader_
            : packetHeaderBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.packetBody_ = packetBodyBuilder_ == null
            ? packetBody_
            : packetBodyBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moon.link.common.domain.protobuf.CompleteMessage) {
        return mergeFrom((com.moon.link.common.domain.protobuf.CompleteMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moon.link.common.domain.protobuf.CompleteMessage other) {
      if (other == com.moon.link.common.domain.protobuf.CompleteMessage.getDefaultInstance()) return this;
      if (other.hasPacketHeader()) {
        mergePacketHeader(other.getPacketHeader());
      }
      if (other.hasPacketBody()) {
        mergePacketBody(other.getPacketBody());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPacketHeaderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPacketBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.moon.link.common.domain.protobuf.PacketHeader packetHeader_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moon.link.common.domain.protobuf.PacketHeader, com.moon.link.common.domain.protobuf.PacketHeader.Builder, com.moon.link.common.domain.protobuf.PacketHeaderOrBuilder> packetHeaderBuilder_;
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     * @return Whether the packetHeader field is set.
     */
    public boolean hasPacketHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     * @return The packetHeader.
     */
    public com.moon.link.common.domain.protobuf.PacketHeader getPacketHeader() {
      if (packetHeaderBuilder_ == null) {
        return packetHeader_ == null ? com.moon.link.common.domain.protobuf.PacketHeader.getDefaultInstance() : packetHeader_;
      } else {
        return packetHeaderBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public Builder setPacketHeader(com.moon.link.common.domain.protobuf.PacketHeader value) {
      if (packetHeaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packetHeader_ = value;
      } else {
        packetHeaderBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public Builder setPacketHeader(
        com.moon.link.common.domain.protobuf.PacketHeader.Builder builderForValue) {
      if (packetHeaderBuilder_ == null) {
        packetHeader_ = builderForValue.build();
      } else {
        packetHeaderBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public Builder mergePacketHeader(com.moon.link.common.domain.protobuf.PacketHeader value) {
      if (packetHeaderBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          packetHeader_ != null &&
          packetHeader_ != com.moon.link.common.domain.protobuf.PacketHeader.getDefaultInstance()) {
          getPacketHeaderBuilder().mergeFrom(value);
        } else {
          packetHeader_ = value;
        }
      } else {
        packetHeaderBuilder_.mergeFrom(value);
      }
      if (packetHeader_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public Builder clearPacketHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      packetHeader_ = null;
      if (packetHeaderBuilder_ != null) {
        packetHeaderBuilder_.dispose();
        packetHeaderBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public com.moon.link.common.domain.protobuf.PacketHeader.Builder getPacketHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPacketHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public com.moon.link.common.domain.protobuf.PacketHeaderOrBuilder getPacketHeaderOrBuilder() {
      if (packetHeaderBuilder_ != null) {
        return packetHeaderBuilder_.getMessageOrBuilder();
      } else {
        return packetHeader_ == null ?
            com.moon.link.common.domain.protobuf.PacketHeader.getDefaultInstance() : packetHeader_;
      }
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moon.link.common.domain.protobuf.PacketHeader, com.moon.link.common.domain.protobuf.PacketHeader.Builder, com.moon.link.common.domain.protobuf.PacketHeaderOrBuilder> 
        getPacketHeaderFieldBuilder() {
      if (packetHeaderBuilder_ == null) {
        packetHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moon.link.common.domain.protobuf.PacketHeader, com.moon.link.common.domain.protobuf.PacketHeader.Builder, com.moon.link.common.domain.protobuf.PacketHeaderOrBuilder>(
                getPacketHeader(),
                getParentForChildren(),
                isClean());
        packetHeader_ = null;
      }
      return packetHeaderBuilder_;
    }

    private com.moon.link.common.domain.protobuf.PacketBody packetBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moon.link.common.domain.protobuf.PacketBody, com.moon.link.common.domain.protobuf.PacketBody.Builder, com.moon.link.common.domain.protobuf.PacketBodyOrBuilder> packetBodyBuilder_;
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     * @return Whether the packetBody field is set.
     */
    public boolean hasPacketBody() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     * @return The packetBody.
     */
    public com.moon.link.common.domain.protobuf.PacketBody getPacketBody() {
      if (packetBodyBuilder_ == null) {
        return packetBody_ == null ? com.moon.link.common.domain.protobuf.PacketBody.getDefaultInstance() : packetBody_;
      } else {
        return packetBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public Builder setPacketBody(com.moon.link.common.domain.protobuf.PacketBody value) {
      if (packetBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packetBody_ = value;
      } else {
        packetBodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public Builder setPacketBody(
        com.moon.link.common.domain.protobuf.PacketBody.Builder builderForValue) {
      if (packetBodyBuilder_ == null) {
        packetBody_ = builderForValue.build();
      } else {
        packetBodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public Builder mergePacketBody(com.moon.link.common.domain.protobuf.PacketBody value) {
      if (packetBodyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          packetBody_ != null &&
          packetBody_ != com.moon.link.common.domain.protobuf.PacketBody.getDefaultInstance()) {
          getPacketBodyBuilder().mergeFrom(value);
        } else {
          packetBody_ = value;
        }
      } else {
        packetBodyBuilder_.mergeFrom(value);
      }
      if (packetBody_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public Builder clearPacketBody() {
      bitField0_ = (bitField0_ & ~0x00000002);
      packetBody_ = null;
      if (packetBodyBuilder_ != null) {
        packetBodyBuilder_.dispose();
        packetBodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public com.moon.link.common.domain.protobuf.PacketBody.Builder getPacketBodyBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPacketBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public com.moon.link.common.domain.protobuf.PacketBodyOrBuilder getPacketBodyOrBuilder() {
      if (packetBodyBuilder_ != null) {
        return packetBodyBuilder_.getMessageOrBuilder();
      } else {
        return packetBody_ == null ?
            com.moon.link.common.domain.protobuf.PacketBody.getDefaultInstance() : packetBody_;
      }
    }
    /**
     * <code>.com.moon.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moon.link.common.domain.protobuf.PacketBody, com.moon.link.common.domain.protobuf.PacketBody.Builder, com.moon.link.common.domain.protobuf.PacketBodyOrBuilder> 
        getPacketBodyFieldBuilder() {
      if (packetBodyBuilder_ == null) {
        packetBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moon.link.common.domain.protobuf.PacketBody, com.moon.link.common.domain.protobuf.PacketBody.Builder, com.moon.link.common.domain.protobuf.PacketBodyOrBuilder>(
                getPacketBody(),
                getParentForChildren(),
                isClean());
        packetBody_ = null;
      }
      return packetBodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.moon.link.common.domain.protobuf.CompleteMessage)
  }

  // @@protoc_insertion_point(class_scope:com.moon.link.common.domain.protobuf.CompleteMessage)
  private static final com.moon.link.common.domain.protobuf.CompleteMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moon.link.common.domain.protobuf.CompleteMessage();
  }

  public static com.moon.link.common.domain.protobuf.CompleteMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompleteMessage>
      PARSER = new com.google.protobuf.AbstractParser<CompleteMessage>() {
    @java.lang.Override
    public CompleteMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CompleteMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompleteMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moon.link.common.domain.protobuf.CompleteMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

