// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

// Protobuf Java Version: 3.25.3
package com.moon.link.common.domain.protobuf;

public final class LinkMessage {
  private LinkMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_link_common_domain_protobuf_PacketHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_link_common_domain_protobuf_PacketHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_link_common_domain_protobuf_PacketBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_link_common_domain_protobuf_PacketBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022link_message.proto\022$com.moon.link.comm" +
      "on.domain.protobuf\"x\n\014PacketHeader\022\016\n\006ap" +
      "p_id\030\001 \001(\007\022\013\n\003uid\030\002 \001(\006\022\r\n\005token\030\003 \001(\t\022\023" +
      "\n\013compression\030\004 \001(\005\022\022\n\nencryption\030\005 \001(\005\022" +
      "\023\n\013messageType\030\006 \001(\005\"l\n\nPacketBody\022\024\n\014fr" +
      "om_user_id\030\001 \001(\003\022\022\n\ntime_stamp\030\002 \001(\003\022\r\n\005" +
      "to_id\030\003 \001(\003\022\024\n\014message_type\030\004 \001(\005\022\017\n\007con" +
      "tent\030\005 \001(\t\"\243\001\n\017CompleteMessage\022I\n\rpacket" +
      "_header\030\001 \001(\01322.com.moon.link.common.dom" +
      "ain.protobuf.PacketHeader\022E\n\013packet_body" +
      "\030\002 \001(\01320.com.moon.link.common.domain.pro" +
      "tobuf.PacketBodyB(\n$com.moon.link.common" +
      ".domain.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_moon_link_common_domain_protobuf_PacketHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_moon_link_common_domain_protobuf_PacketHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_link_common_domain_protobuf_PacketHeader_descriptor,
        new java.lang.String[] { "AppId", "Uid", "Token", "Compression", "Encryption", "MessageType", });
    internal_static_com_moon_link_common_domain_protobuf_PacketBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_moon_link_common_domain_protobuf_PacketBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_link_common_domain_protobuf_PacketBody_descriptor,
        new java.lang.String[] { "FromUserId", "TimeStamp", "ToId", "MessageType", "Content", });
    internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_link_common_domain_protobuf_CompleteMessage_descriptor,
        new java.lang.String[] { "PacketHeader", "PacketBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
