// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

// Protobuf Java Version: 3.25.3
package com.moon.link.common.domain.protobuf;

public interface PacketHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moon.link.common.domain.protobuf.PacketHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * app_id：业务线 ID，比如聊天业务、系统通知业务 fixed32 表示固定长度占用 32 / 8 = 4 个字节
   * </pre>
   *
   * <code>fixed32 app_id = 1;</code>
   * @return The appId.
   */
  int getAppId();

  /**
   * <pre>
   * uid：当前用户 ID
   * </pre>
   *
   * <code>fixed64 uid = 2;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <pre>
   * token：用户登录凭证 16 字节
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * token：用户登录凭证 16 字节
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   * compression：是否压缩，0 不压缩，1 gzip 1 字节
   * </pre>
   *
   * <code>int32 compression = 4;</code>
   * @return The compression.
   */
  int getCompression();

  /**
   * <pre>
   * encryption：是否加密，0 不加密，1 AES 1字节
   * </pre>
   *
   * <code>int32 encryption = 5;</code>
   * @return The encryption.
   */
  int getEncryption();

  /**
   * <pre>
   * messageType：消息类型，比如登录、心跳、私聊、群聊 2 字节
   * 0-客户端登录，1-心跳，2-ack，3-强制下线,4-私聊，
   * 5-群聊，6-系统消息，7-集群机器连接请求，8-集群机器转发下行消息
   * </pre>
   *
   * <code>int32 messageType = 6;</code>
   * @return The messageType.
   */
  int getMessageType();
}
