// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

// Protobuf Java Version: 3.25.3
package com.moon.link.common.domain.protobuf;

/**
 * Protobuf type {@code com.moon.link.common.domain.protobuf.PacketBody}
 */
public final class PacketBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.moon.link.common.domain.protobuf.PacketBody)
    PacketBodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PacketBody.newBuilder() to construct.
  private PacketBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PacketBody() {
    content_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PacketBody();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_PacketBody_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_PacketBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moon.link.common.domain.protobuf.PacketBody.class, com.moon.link.common.domain.protobuf.PacketBody.Builder.class);
  }

  public static final int FROM_USER_ID_FIELD_NUMBER = 1;
  private long fromUserId_ = 0L;
  /**
   * <pre>
   * from_user_id：发送人 ID
   * </pre>
   *
   * <code>int64 from_user_id = 1;</code>
   * @return The fromUserId.
   */
  @java.lang.Override
  public long getFromUserId() {
    return fromUserId_;
  }

  public static final int TIME_STAMP_FIELD_NUMBER = 2;
  private long timeStamp_ = 0L;
  /**
   * <pre>
   * time_stamp：消息时间戳
   * </pre>
   *
   * <code>int64 time_stamp = 2;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public long getTimeStamp() {
    return timeStamp_;
  }

  public static final int TO_ID_FIELD_NUMBER = 3;
  private long toId_ = 0L;
  /**
   * <pre>
   * to_id：接收人 ID
   * </pre>
   *
   * <code>int64 to_id = 3;</code>
   * @return The toId.
   */
  @java.lang.Override
  public long getToId() {
    return toId_;
  }

  public static final int MESSAGE_TYPE_FIELD_NUMBER = 4;
  private int messageType_ = 0;
  /**
   * <pre>
   * message_type：业务消息类型
   * </pre>
   *
   * <code>int32 message_type = 4;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public int getMessageType() {
    return messageType_;
  }

  public static final int CONTENT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <pre>
   * content：消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * content：消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fromUserId_ != 0L) {
      output.writeInt64(1, fromUserId_);
    }
    if (timeStamp_ != 0L) {
      output.writeInt64(2, timeStamp_);
    }
    if (toId_ != 0L) {
      output.writeInt64(3, toId_);
    }
    if (messageType_ != 0) {
      output.writeInt32(4, messageType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fromUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, fromUserId_);
    }
    if (timeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timeStamp_);
    }
    if (toId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, toId_);
    }
    if (messageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, messageType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moon.link.common.domain.protobuf.PacketBody)) {
      return super.equals(obj);
    }
    com.moon.link.common.domain.protobuf.PacketBody other = (com.moon.link.common.domain.protobuf.PacketBody) obj;

    if (getFromUserId()
        != other.getFromUserId()) return false;
    if (getTimeStamp()
        != other.getTimeStamp()) return false;
    if (getToId()
        != other.getToId()) return false;
    if (getMessageType()
        != other.getMessageType()) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFromUserId());
    hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeStamp());
    hash = (37 * hash) + TO_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getToId());
    hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.moon.link.common.domain.protobuf.PacketBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.moon.link.common.domain.protobuf.PacketBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moon.link.common.domain.protobuf.PacketBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moon.link.common.domain.protobuf.PacketBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.moon.link.common.domain.protobuf.PacketBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.moon.link.common.domain.protobuf.PacketBody)
      com.moon.link.common.domain.protobuf.PacketBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_PacketBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_PacketBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.link.common.domain.protobuf.PacketBody.class, com.moon.link.common.domain.protobuf.PacketBody.Builder.class);
    }

    // Construct using com.moon.link.common.domain.protobuf.PacketBody.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromUserId_ = 0L;
      timeStamp_ = 0L;
      toId_ = 0L;
      messageType_ = 0;
      content_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moon.link.common.domain.protobuf.LinkMessage.internal_static_com_moon_link_common_domain_protobuf_PacketBody_descriptor;
    }

    @java.lang.Override
    public com.moon.link.common.domain.protobuf.PacketBody getDefaultInstanceForType() {
      return com.moon.link.common.domain.protobuf.PacketBody.getDefaultInstance();
    }

    @java.lang.Override
    public com.moon.link.common.domain.protobuf.PacketBody build() {
      com.moon.link.common.domain.protobuf.PacketBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moon.link.common.domain.protobuf.PacketBody buildPartial() {
      com.moon.link.common.domain.protobuf.PacketBody result = new com.moon.link.common.domain.protobuf.PacketBody(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.moon.link.common.domain.protobuf.PacketBody result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromUserId_ = fromUserId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timeStamp_ = timeStamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.toId_ = toId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.messageType_ = messageType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.content_ = content_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moon.link.common.domain.protobuf.PacketBody) {
        return mergeFrom((com.moon.link.common.domain.protobuf.PacketBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moon.link.common.domain.protobuf.PacketBody other) {
      if (other == com.moon.link.common.domain.protobuf.PacketBody.getDefaultInstance()) return this;
      if (other.getFromUserId() != 0L) {
        setFromUserId(other.getFromUserId());
      }
      if (other.getTimeStamp() != 0L) {
        setTimeStamp(other.getTimeStamp());
      }
      if (other.getToId() != 0L) {
        setToId(other.getToId());
      }
      if (other.getMessageType() != 0) {
        setMessageType(other.getMessageType());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fromUserId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              timeStamp_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              toId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              messageType_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long fromUserId_ ;
    /**
     * <pre>
     * from_user_id：发送人 ID
     * </pre>
     *
     * <code>int64 from_user_id = 1;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public long getFromUserId() {
      return fromUserId_;
    }
    /**
     * <pre>
     * from_user_id：发送人 ID
     * </pre>
     *
     * <code>int64 from_user_id = 1;</code>
     * @param value The fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserId(long value) {

      fromUserId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * from_user_id：发送人 ID
     * </pre>
     *
     * <code>int64 from_user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fromUserId_ = 0L;
      onChanged();
      return this;
    }

    private long timeStamp_ ;
    /**
     * <pre>
     * time_stamp：消息时间戳
     * </pre>
     *
     * <code>int64 time_stamp = 2;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <pre>
     * time_stamp：消息时间戳
     * </pre>
     *
     * <code>int64 time_stamp = 2;</code>
     * @param value The timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStamp(long value) {

      timeStamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * time_stamp：消息时间戳
     * </pre>
     *
     * <code>int64 time_stamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timeStamp_ = 0L;
      onChanged();
      return this;
    }

    private long toId_ ;
    /**
     * <pre>
     * to_id：接收人 ID
     * </pre>
     *
     * <code>int64 to_id = 3;</code>
     * @return The toId.
     */
    @java.lang.Override
    public long getToId() {
      return toId_;
    }
    /**
     * <pre>
     * to_id：接收人 ID
     * </pre>
     *
     * <code>int64 to_id = 3;</code>
     * @param value The toId to set.
     * @return This builder for chaining.
     */
    public Builder setToId(long value) {

      toId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * to_id：接收人 ID
     * </pre>
     *
     * <code>int64 to_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearToId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      toId_ = 0L;
      onChanged();
      return this;
    }

    private int messageType_ ;
    /**
     * <pre>
     * message_type：业务消息类型
     * </pre>
     *
     * <code>int32 message_type = 4;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }
    /**
     * <pre>
     * message_type：业务消息类型
     * </pre>
     *
     * <code>int32 message_type = 4;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(int value) {

      messageType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * message_type：业务消息类型
     * </pre>
     *
     * <code>int32 message_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      messageType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * content：消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * content：消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * content：消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * content：消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * content：消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.moon.link.common.domain.protobuf.PacketBody)
  }

  // @@protoc_insertion_point(class_scope:com.moon.link.common.domain.protobuf.PacketBody)
  private static final com.moon.link.common.domain.protobuf.PacketBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moon.link.common.domain.protobuf.PacketBody();
  }

  public static com.moon.link.common.domain.protobuf.PacketBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PacketBody>
      PARSER = new com.google.protobuf.AbstractParser<PacketBody>() {
    @java.lang.Override
    public PacketBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PacketBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PacketBody> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moon.link.common.domain.protobuf.PacketBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

