// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

// Protobuf Java Version: 3.25.3
package com.moon.link.common.domain.protobuf;

public interface PacketBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moon.link.common.domain.protobuf.PacketBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * from_user_id：发送人 ID
   * </pre>
   *
   * <code>int64 from_user_id = 1;</code>
   * @return The fromUserId.
   */
  long getFromUserId();

  /**
   * <pre>
   * time_stamp：消息时间戳
   * </pre>
   *
   * <code>int64 time_stamp = 2;</code>
   * @return The timeStamp.
   */
  long getTimeStamp();

  /**
   * <pre>
   * to_id：接收人 ID
   * </pre>
   *
   * <code>int64 to_id = 3;</code>
   * @return The toId.
   */
  long getToId();

  /**
   * <pre>
   * message_type：业务消息类型
   * </pre>
   *
   * <code>int32 message_type = 4;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <pre>
   * content：消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * content：消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
